
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/shequnke?useUnicode=true&characterEncoding=utf-8
#mybatisplus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.cooplan.shiro_demo.pojo

